version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "BP3-pipeline"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-mnr7jxaobo2t"
s3_prefix = "BP3-pipeline"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ComputeType=BUILD_GENERAL1_SMALL EnvironmentType=LINUX_CONTAINER SourceCodeProvider=GitHub GitHubOwner=emma1710 GitHubRepo=BP3 GitHubBranch=master CodeCommitRepo= CodeCommitBranch=master DeployParameterOverrides={} DeployStackName=BP3-deploy DeployRoleName=DeployRole IntegTestRoleName= BuildSpecFilePath=buildspec.yaml IntegTestBuildSpecFilePath=buildspec-integ-test.yaml PublishToSAR=false"

